### PR TITLE
Feature/update apis to v1

### LINKED ISSUE #826: API moved to /v1
#### Proposed solution

There are some more breaking changes in the backend from this PR https://github.com/CSCfi/metadata-submitter/pull/476

- API is now under `/v1`
- `/logout` doesn't redirect to frontend any more, it returns 204
- Only API routes are checked for session authentication, so frontend now has to check it. Other routes are public

Public routes are:
- `/aai`
- `/callback`
- `/logout`
- `/health`
- `/static`
- `/` - with catch-all, so any routes not matching other routes will return the frontend files, so maybe frontend needs to handle routing differently
#### DoD (Definition of Done)

Frontend works against backend commit `be0002c`, which is the last commit in `develop` at the time of creating this issue.

#### Testing

Tests pass again ^^

### PR DESCRIPTION
**Pull request by lilachic**
### Description

Add /v1 in API urls  to adapt backend change.

### Related issues

Fixes #826

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update (this needs a follow up PR)

### Changes Made

The frontend uses now following APIs
      "/v1/objects"
      "/v1/schemas"
      "/v1/validate"
      "/v1/submit"
      "/v1/submissions"
      "/v1/publish"
      "/v1/drafts"
      "/aai"
      "/callback"
      "/logout"
      "/v1/users"
      "/v1/templates"

Added a line about /v1 in API urls in CHANGELOG.
Rename cookie MTD_SESSION to AOIHTTP_SESSION in e2e login test.

### Testing

- [x] Unit Tests
- [x] Integration Tests

### CODE REVIEW

**Comment by csc-felipe** [comment]
Rebased and pushed, to see test results.

**Comment by csc-felipe** [comment]
Had to update node, with new npm, same version as github actions, I get the same errors:

```
$ nvm install 16
$ nvm use 16.15.1
$ node --version
v16.15.1
$ npm --version
8.11.0
```

**Comment by csc-felipe** [comment]
Looking at the changes made, I think it still needs something to be done about the routing, and checking that user is logged in. Assuming these were not there before.

**Comment by lilachic** [comment]
The e2e tests to pass need the https://github.com/CSCfi/metadata-submitter/pull/554 merged in the backed develop branch. Locally with that branch the tests passes.

**Comment by csc-felipe** [comment]
> The e2e tests to pass need the https://github.com/CSCfi/metadata-submitter/pull/554 merged in the backed develop branch. Locally with that branch the tests passes.

Done

**Comment by lilachic** [comment]
No tests fail for getting 400 from v1/schemas/datacite .

**Comment by csc-felipe** [comment]
> No tests fail for getting 400 from v1/schemas/datacite .

I'm sorry, but I didn't understand. Do you mean that `/v1/schemas/datacite` still gives `HTTP 400`?

**Pull request closed without merging**
