### PR TITLE
Feature/handling errors

### PR DESCRIPTION
**Pull request by hannyle**
### Description

Errors 401, 403, 404, 500 are handled in separate pages
With errors 401, 403 users are linked back to Main Page or Home Page

### Type of change

- [x] New feature (non-breaking change which adds functionality)

### Changes Made

- Create 401 error handling page
- Create 403 error handling page
- Create Container for wrapping error handling pages
- Unit tests for error pages 401, 403, 404, 500

### Testing

- [x] Unit Tests
- [x] Needs testing (start an issue or do a follow up PR about it)

### CODE REVIEW

**Review by blankdots — COMMENTED** [review]
The pages added and the code look very good. I have 2 suggestions this can be improved both from a design and functionality perspective.

Design (would be nice to be part of this PR, if possible)

image

I think for errors such as `401`, `403` and `500` we don't need the top bar (image above) and we can have a simple centred box that  contains the logo and displays the current message and returns to main page (as is right now with the count down). We can also make use of https://material-ui.com/components/alert/#simple-alerts  to add some eye candy to the message.

For top bar removal this might help: https://github.com/CSCfi/metadata-submitter-frontend/blob/master/src/components/Nav.js#L48-L50

---

(this can be done in a different PR)
From a functionality perspective we need to catch `401`, `403`, `500` etc. errors from back-end and display the proper message which currently they are not

For API calls in `/services` we can probably make use of this: https://github.com/infinitered/apisauce#adding-monitors and check the status.

**Comment by blankdots** [comment]
If we cannot catch some errors in the front-end, we might also need to redirect from back-end e.g.

1. have back-end running (develop branch)
2. go to localhost:3000/folders/1
3. see a json response

What should be at step 3 is the corresponding error page as back-end checks each request user is authenticated.

**Comment by hannyle** [comment]
Ok, it's good you pointed out that we should the top bar. I can improve the design part within this PR.
For the errors catching, I can start with a new issue to make it clear.

**Comment by hannyle** [comment]
I also added custom colors for error pages according CSC's color theme

**Review by blankdots — APPROVED** [review]
no more comments, just that looks good!

**Review by csc-jm — APPROVED** [review]
Error pages look good

**Review by blankdots — APPROVED** [review]

**Comment by blankdots** [comment]
merging this, if anything arises we can do another PR to fix it.

**Pull request merged**
