### PR TITLE
Feature/show object details

### LINKED ISSUE #410: show details on draft and published should provide a summary
#### Description

As a user i want to see a summary of the object without opening it. 
continuation of https://github.com/CSCfi/metadata-submitter-frontend/issues/138

For getting the details it is an API call to the back-end with the object id to the proper schema.

#### DoD (Definition of Done)

`Show details` on `draft` and `published` folders provide a summary of the object in a table

#### Testing

unit and integration testing

### PR DESCRIPTION
**Pull request by saulipurhonen**
### Description

Display object details inside folder.

### Related issues

Closes #410 

### Type of change

- [x] New feature (non-breaking change which adds functionality)

### Changes Made

- Custom JSON schema parser for object details
- Collapse details

### Testing

- [x] Unit Tests
- [x] Integration Tests

### CODE REVIEW

**Comment by saulipurhonen** [comment]
Details UX isn't perfect as it is since long lists of details can be hard to view as user. One option could be tabbed layout. 
Eg. on `Study` tab items could be `Study Description`, `Study Links`, `Study Attributes` & `Description for Center`

Layout can be handled either on this or some other PR.

**Comment by lilachic** [comment]
Maybe UX styling belongs to adapting CSC styling?

**Review by hannyle — APPROVED** [review]
Looks very good to me. Well done! 

I think this should be rebased onto `develop` branch as well.
A minor thing is some functions kinda overlap between `JSONSchemaParser` files, maybe we could just reuse them ? (for e.g. `dereferenceSchema`, `pathToName`)

**Review by lilachic — APPROVED** [review]
The details look good to me.

**Comment by saulipurhonen** [comment]
> Looks very good to me. Well done!
> 
> I think this should be rebased onto `develop` branch as well.
> A minor thing is some functions kinda overlap between `JSONSchemaParser` files, maybe we could just reuse them ? (for e.g. `dereferenceSchema`, `pathToName`)

Good points. Going to implement these changes soon.

**Comment by saulipurhonen** [comment]
> Looks very good to me. Well done!
> 
> I think this should be rebased onto `develop` branch as well.
> A minor thing is some functions kinda overlap between `JSONSchemaParser` files, maybe we could just reuse them ? (for e.g. `dereferenceSchema`, `pathToName`)

Introduced shared JSON schema utilities file and rebased with `develop`

**Review by hannyle — APPROVED** [review]

**Pull request merged**
