### PR TITLE
Feature/edit publish draft folder

### LINKED ISSUE #138: Edit and Publish a folder (for draft only)
#### Proposed solution

Currently in the Home view, when we select a **draft** folder that contains objects, we should be able to `Edit` and `Publish` that folder.

`Edit` and `Publish` buttons of a published folder need more discussion.

image
#### DoD (Definition of Done)

In **draft** (unpublished) folder:
- Click `Edit` folder should open the Edit view for the folder
- Click `Publish` folder should publish the folder

In **published** folder:
- we cannot not `Edit` folder and `Published` folder buttons shouldn't be visible
- `Delete` should not be possible.

#### Testing

- Integration test, e2e test, peer review

### PR DESCRIPTION
**Pull request by saulipurhonen**
### Description

Edit & publish folder functionality for draft folders. Show tooltip for folders without submitted objects.

### Related issues

Closes #138 

### Type of change

- [x] New feature (non-breaking change which adds functionality)

### Changes Made

- Edit button functionality in draft folder view
- Disable `Publish` button in draft folder if no submitted objects
- Show tooltip with icon in draft folder if no submitted objects
- Publish functionality for draft folder
- Hide `Edit` & `Publish` buttons from published folders
- Hide `Delete` button from objects in published folder
- Common tooltip theme
- Reset `objectType` and `submissionFolder` on `Create Submission` button click

### Testing

- [x] E2E Tests
- [x] Integration Tests

### CODE REVIEW

**Comment by blankdots** [comment]
seems this needs a rebase as the #364 has been merged

**Review by blankdots — CHANGES_REQUESTED** [review]
image

The edit button for the folder works, however are we not solving the edit  for individual objects as part of this issue ?
I clicked on edit and nothing happened. Delete worked but `edit` did not for me, and nothing in the console.

Peek 2021-08-16 18-32

--- 

image

Empty draft folders are a special case so I suggest we have a button in the middle `Add objects to folder` that has similar functionality to `Edit` folder

**Comment by saulipurhonen** [comment]
> The edit button for the folder works, however are we not solving the edit for individual objects as part of this issue ?
> I clicked on edit and nothing happened. Delete worked but `edit` did not for me, and nothing in the console.

Good call. I was blindly following the original issue to enable actions only for the folder, not objects. I'll enable object actions also.

> Empty draft folders are a special case so I suggest we have a button in the middle `Add objects to folder` that has similar functionality to `Edit` folder

This a good idea, I'll implement.

**Comment by hannyle** [comment]
Apart from what Stefan mentioned, looks good to me. Looking forward to the additional changes :)

**Comment by saulipurhonen** [comment]
I added both edit functionality for objects in draft folders and button for adding objects for empty folders.
Tests are updated for new functionalities.

**Comment by saulipurhonen** [comment]
> The edit button for the folder works, however are we not solving the edit for individual objects as part of this issue ?
> I clicked on edit and nothing happened. Delete worked but `edit` did not for me, and nothing in the console.

Edit button now functional. Disabled `view` and `show details` buttons since those don't have functionality yet.

> Empty draft folders are a special case so I suggest we have a button in the middle `Add objects to folder` that has similar functionality to `Edit` folder

Button added for empty folders

**Comment by blankdots** [comment]
2 other things, and not sure if we should handle as part of this issue.
DAC uses Main contact
image

can we show the same thing in:
image

also DAC is an acronym should be all uppercase

**Comment by saulipurhonen** [comment]
> 2 other things, and not sure if we should handle as part of this issue.
> DAC uses Main contact

> also DAC is an acronym should be all uppercase

I think we can add these into this PR.

**Comment by saulipurhonen** [comment]
> > 2 other things, and not sure if we should handle as part of this issue.
> > DAC uses Main contact
> 
> > also DAC is an acronym should be all uppercase
> 
> I think we can add these into this PR.

Changes added.

**Review by blankdots — APPROVED** [review]

**Review by hannyle — APPROVED** [review]
LGTM

**Pull request merged**
