### PR TITLE
Feature/date picker

### PR DESCRIPTION
**Pull request by hannyle**
### Description

In DOI form > `Dates`, adding Date picker to pick a date or a date-range.

### Related issues

Closes https://github.com/CSCfi/metadata-submitter-frontend/issues/498

### Type of change

- [x] New feature (non-breaking change which adds functionality)

### Changes Made

- Implemented using MUI v.5 `DatePicker` component
- Customised the `DatePicker` to work in different screen sizes (the standard way of implementing it now in MUI v.5 has a bug with smaller screens)(_took me a while to realise this issue_)
- Followed up PR https://github.com/CSCfi/metadata-submitter-frontend/pull/543, `FormDatePicker` has been updated with MUI v.5's new styling ways for its specific components (using `sx` and `styled`)
- Made two different components for selecting `Start` and `End` dates
- Used `moment.js` (which was chosen and included in the library to used with `DatePicker`) to format the dates 
- Handled input dates according to RKMS-ISO8601 guidelines for date ranges
- Added e2e test for selecting dates and saving DOI form successfully

### Testing

- [x] Integration Tests

### CODE REVIEW

**Review by blankdots — APPROVED** [review]
works like expected.

**Comment by blankdots** [comment]
maybe we can rebase this, so we can merge it ?

**Review by lilachic — APPROVED** [review]
LGTM,  :) some wrapping to get calendar there. Maybe when styling we could improve the error message that now says "Please select an item in the list"  to something saying about the calendar.

**Comment by hannyle** [comment]
The PR is rebased and will be merged to `develop`

**Pull request merged**
