### PR TITLE
Feature/form and xml changes

### PR DESCRIPTION
**Pull request by hannyle**
### Description

Introduced new structure of  **Form**, new way of showing **Tooltip** and new way to upload and show **XML File**.

### Related issues

Closes  https://github.com/CSCfi/metadata-submitter-frontend/issues/540, https://github.com/CSCfi/metadata-submitter-frontend/issues/541, https://github.com/CSCfi/metadata-submitter-frontend/issues/787

### Type of change

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Changes Made

- Converted the **Form** into new layout by mainly refactoring `FormSection`  in `WizardJSONSchemaParser.tsx`
- Remade **Tooltip** with reusable component `DisplayDescription`, limited the default description text length to 60 chars with option to **Read more/Expand** text
- Added **Options** including **Upload XML** and **Clear form** to **Form** 
- Changed form's action buttons to **Save as draft** and **Mark as ready**
- Added modal for selecting/drag-dropping XML file
- Added a new page for showing information of selected XML file
- Fixed a bug about refreshing and starting a new form whenever we click `Add <object>` button
- Update unit test for **Tooltip** 
- Update e2e tests for **Form**

### Testing

- [x] Unit Tests
- [x] Integration Tests

### CODE REVIEW

**Comment by hannyle** [comment]
e2e test for Upload XML will be implementation in another PR with this issue: https://github.com/CSCfi/metadata-submitter-frontend/issues/652

**Comment by lilachic** [comment]
Wondering if this meant the tooltips to be rendered on the left of the question mark icon
Screenshot 2022-05-27 at 18 02 30
?

**Comment by saulipurhonen** [comment]
Maybe change cursor to "pointer" when hovering "Read more/Expand" link?
image

**Comment by saulipurhonen** [comment]
> Wondering if this meant the tooltips to be rendered on the left of the question mark icon Screenshot 2022-05-27 at 18 02 30 ?

This seems to be related to browser size. Tooltip is rendered on right side of the indicator on larger resolutions.

**Review by saulipurhonen — APPROVED** [review]
Well written and easy to understand. LGTM!

**Comment by hannyle** [comment]
> > Wondering if this meant the tooltips to be rendered on the left of the question mark icon
> 
> This seems to be related to browser size. Tooltip is rendered on right side of the indicator on larger resolutions.

Yes that's related to browser size.

**Pull request merged**
