### PR TITLE
Feature/saved objects info

### LINKED ISSUE #68: Implement showing info about saved objects in wizard
#### Proposed solution

Saved objects should be listed on the right side of screen (like in UI sketch version 4). 

#### DoD (Definition of Done)

Objects are listed

### PR DESCRIPTION
**Pull request by saulipurhonen**
### Description

Added list for submissions in Add Objects -step. Possibility to delete objects from list.

### Related issues

Fixes #68 

### Type of change

- [x] New feature (non-breaking change which adds functionality)

### Changes Made

- List submissions by object type
- Enable deletion from both state and database
- Show "Added!" toast after successful object save

### Testing

- [x] Integration Tests

### CODE REVIEW

**Comment by saulipurhonen** [comment]
Note: Objects list isn't responsive just yet.

**Comment by lilachic** [comment]
Looks ok for me. Just something in appearance, in narrow screen the delete x is rendered on top of the list text. In the List header there is "Submitted study forms" here Submitted study items. If I also upload XML files I don't detect which are which, maybe the ID tells.

**Review by lilachic — APPROVED** [review]

**Review by blankdots — APPROVED** [review]
tested and looks ok. We can touch up any css in feature version

**Comment by blankdots** [comment]
@lilachic good point can you add an issue about it ?

**Pull request merged**
