### PR TITLE
release 0.9.0

### PR DESCRIPTION
**Pull request by blankdots**
### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Changes Made

See PRs #166 #168 #171 #178 #179 #180 #182 #183 #184 #185

- constants variables for objects and data types 
- custom hook for draft saving
- bugfix forms
- production deployment improvements
- update packages
- UI improvements

### Testing

- [x] Unit Tests
- [x] Integration Tests

### Mentions

this is needed so that we can release back-end code from https://github.com/CSCfi/metadata-submitter/pull/206

added with this dependabot to manage/watch/update dependencies automatically

### CODE REVIEW

**Comment by hannyle** [comment]
Looks good to me.

Besides, there is one bug related to  `saveDraftHook` in PR https://github.com/CSCfi/metadata-submitter-frontend/pull/185.
I fixed it also in PR https://github.com/CSCfi/metadata-submitter-frontend/pull/187

Should we keep it like this and merge the fix into the next release ?

**Review by hannyle — APPROVED** [review]

**Comment by blankdots** [comment]
@hannyle i think we can wait for #187 to get merged so no rush

**Review by lilachic — APPROVED** [review]

**Comment by lilachic** [comment]
Something I noticed in console: unknown format "email" ignored in schema at path "#/definitions/contact/properties/email"
Comes sometimes when in DAC clicking: Fill Form > Contacts > Add new Item > -

**Comment by blankdots** [comment]
@lilachic i think this is what @hannyle also mentioned Monday and as I mentioned then the AJV does not know that format, and the processing we do on those formats might not be aware of it. I don't think this is caused by this PR and should be treated as a separate issue.

It might be as simple to use this: https://github.com/ajv-validator/ajv-formats or some custom processing is needed

**Pull request merged**
