### PR TITLE
Tests for error pages

### LINKED ISSUE #120: Integration tests for error pages
#### Description

as a follow-up of https://github.com/CSCfi/metadata-submitter-frontend/issues/117 and dependent on https://github.com/CSCfi/metadata-submitterd/issues/170 we need integration tests for error pages

#### DoD (Definition of Done)

cypress  integration tests for error pages

#### Testing

integration tests defined and passing

### PR DESCRIPTION
**Pull request by saulipurhonen**
### Description

Test that error situations trigger corresponding error pages.

### Related issues

Closes #120 

### Type of change

- [x] New feature (non-breaking change which adds functionality)

### Changes Made

- Intercept 403 and 500 errors
- Check that error pages render

### Testing

- [x] Integration Tests

### CODE REVIEW

**Review by blankdots — APPROVED** [review]

**Comment by hannyle** [comment]
Cypress tests didn't pass on my local machine.  First of them  was an error in `parseFormSchema` in `WizardAjvResolver.js`. Probably we can try to rebase it on the latest `develop` branch ?

**Comment by saulipurhonen** [comment]
> Cypress tests didn't pass on my local machine. First of them was an error in `parseFormSchema` in `WizardAjvResolver.js`. Probably we can try to rebase it on the latest `develop` branch ?
> At least my tests all passed in current `develop`

@hannyle you might need to clear browser cache, also check AJV version that it matches the one in `package.json`. AJV package update had some breaking changes and on my local the browser cache had to be cleared after npm install.

**Comment by hannyle** [comment]
> > Cypress tests didn't pass on my local machine. First of them was an error in `parseFormSchema` in `WizardAjvResolver.js`. Probably we can try to rebase it on the latest `develop` branch ?
> > At least my tests all passed in current `develop`
> 
> @hannyle you might need to clear browser cache, also check AJV version that it matches the one in `package.json`. AJV package update had some breaking changes and on my local the browser cache had to be cleared after npm install.

okay, I think I have the correct Ajv version. I also did try reinstall and clear cache, sadly the tests still failed. However when I locally rebased the branch all the tests passed. :-/

**Review by hannyle — APPROVED** [review]
I will find out more the issue in my local env. 
Otherwise the test was nicely done.

**Comment by saulipurhonen** [comment]
> > > Cypress tests didn't pass on my local machine. First of them was an error in `parseFormSchema` in `WizardAjvResolver.js`. Probably we can try to rebase it on the latest `develop` branch ?
> > > At least my tests all passed in current `develop`
> > 
> > 
> > @hannyle you might need to clear browser cache, also check AJV version that it matches the one in `package.json`. AJV package update had some breaking changes and on my local the browser cache had to be cleared after npm install.
> 
> okay, I think I have the correct Ajv version. I also did try reinstall and clear cache, sadly the tests still failed. However when I locally rebased the branch, all the tests passed. :-/

I think I've found a solution for this. On this branch we have AJV v8 but `parseErrorSchema` has incorrect propery name `dataPath` from earlier version. On your local `dataPath` doesn't correspond to anything and it should be `instancePath` as stated in AJV changelog.

I'll rebase and push into this branch.

**Comment by hannyle** [comment]
> > > 
> > > @hannyle you might need to clear browser cache, also check AJV version that it matches the one in `package.json`. AJV package update had some breaking changes and on my local the browser cache had to be cleared after npm install.
> > 
> > 
> > okay, I think I have the correct Ajv version. I also did try reinstall and clear cache, sadly the tests still failed. However when I locally rebased the branch, all the tests passed. :-/
> 
> I think I've found a solution for this. On this branch we have AJV v8 but `parseErrorSchema` has incorrect propery name `dataPath` from earlier version. On your local `dataPath` doesn't correspond to anything and it should be `instancePath` as stated in AJV changelog.
> 
> I'll rebase and push into this branch.

Right, the error was at `dataPath` in `parseErrorSchema` function. The rebase did help and my tests smoothly passed. Thanks!

**Review by lilachic — APPROVED** [review]

**Pull request merged**
