### PR TITLE
Feature/get organizations from ror api

### LINKED ISSUE #176: For organization fields use Research Organization Registry (ROR) API
#### Description

For organization fields to allow a more precise selection use: https://github.com/ror-community/ror-api 

#### DoD (Definition of Done)

If there is an organization field (and maybe Center Name - TBD) make an API call to search and select the organization from ROR API

#### Testing

Unit testing (maybe mock ROR API response) and integration testing if needed.

### PR DESCRIPTION
**Pull request by saulipurhonen**
### Description

Forms with `organisation` property in form schema are treated as autocomplete fields. Data is fetched from ROR API.

### Related issues

Closes #176 

### Type of change

- [x] New feature (non-breaking change which adds functionality)

### Changes Made

- Use MaterialUI autocomplete field if field name is among `autoCompleteIdentifiers`. 
- More straightforward form data assertion and form reset. Helps when rendering edited form with autocomplete field.
- Search ROR API for matching organisation name
- Autocomplete + tooltip icon combination styling and positioning
- Jest tests with Mock Service Worker library
- Fixed E2E tests to work with autocomplete field

### Testing

- [x] Unit Tests
- [x] Integration Tests

### CODE REVIEW

**Review by blankdots — APPROVED** [review]
seems to provide desired functionality, we can improve styles after we introduce new styles
image

**Review by blankdots — COMMENTED** [review]
maybe to the tooltip we can add that we are using `ror.org` for a standardised list of institutions, that would be ideal, if possible

**Comment by saulipurhonen** [comment]
> maybe to the tooltip we can add that we are using `ror.org` for a standardised list of institutions, that would be ideal, if possible

Sounds good to me. Would next sentence fit: `Organisations provided by ror.org`? And this text after the current description?

**Comment by blankdots** [comment]
yes sounds ok, if we can make ror.org hyperlink even better

**Comment by saulipurhonen** [comment]
> yes sounds ok, if we can make ror.org hyperlink even better

Hyperlink would need tooltip to stay open when user moves cursor out from icon. MUI has option for interactive tooltips, I'll look into it.

**Review by blankdots — APPROVED** [review]

**Review by hannyle — APPROVED** [review]
Looks good to me!
I think we can also mock the organisation data with cypress, I'm curious is there any other good reasons that we have it in unit test here?

**Comment by blankdots** [comment]
> I think we can also mock the organisation data with cypress, I'm curious is there any other good reasons that we have it in unit test here?

that is a fair point

**Comment by saulipurhonen** [comment]
> Looks good to me!
> I think we can also mock the organisation data with cypress, I'm curious is there any other good reasons that we have it in unit test here?

Main reason for testing organisation data for autocomplete in unit test was to reduce weight on E2E CI pipeline. To be honest I'm getting a bit anxious when Cypress CI pipeline runs and fails multiple times with inconsistent reasons :/

However Cypress test for this feature could be handy since unit test doesn't test database interaction.

**Review by lilachic — APPROVED** [review]

**Pull request merged**
