### PR TITLE
Feature/auto save draft

### LINKED ISSUE #67: Implement (auto-)saving draft versions of folders
#### Proposed solution

If user currently changes away from form, alert is shown asking if user want's to save the form. Save doesn't do anything, so implement draft possibility. 

User should also be notified somehow that they have non-finished versions of forms available. 

In best case form is auto-saved every now and then and saving is reported to user via notification.

#### DoD (Definition of Done)

Saving draft versions is possible.

### PR DESCRIPTION
**Pull request by saulipurhonen**
### Description

Enables draft saving functionality via dialogs and by auto-saving with timer.
Folder publish is done through /publish endpoint. This call removes drafts from the folder.
Draft save notification and connection errors are shown through status message handler.

NOTE: To get authorization, you need to start from login page.

### Related issues

Closes #67 & #101

### Type of change

- [x] New feature (non-breaking change which adds functionality)

### Changes Made

- Login link through backend port to get authorization.
- Enabled draft save with dedicated function
- Start timer when form changes, timer resets on every key press
- Reset timer when dialog is open or draft is saved
- Slice for status message (status, response, prefix text)
- Slice for alert. Helps with stopping auto-save timer
- Show draft related status messages in wizard root
- Added "/publish" -endpoint into proxy config

### Testing

- [x] Needs testing (start an issue or do a follow up PR about it)

### Mentions

Cheers to @blankdots for helping with backend related problems.

### CODE REVIEW

**Comment by saulipurhonen** [comment]
I introduced status message handler in wizard root component because we need to inform when draft is saved. This component is fired if statusDetails slice has updates. Status details are updated only when draft is saved but this same logic could be used in other places where status message component is called.
This would reduce need to have status message component only in wizard root.

**Review by blankdots — COMMENTED** [review]
identified: https://github.com/CSCfi/metadata-submitter/pull/164 and fixed

**Review by blankdots — COMMENTED** [review]
I am not sure where to recover the saved draft objects. I am expecting them to be in `Choose existing object`, but I assume this can be done in a different PR.

**Review by blankdots — APPROVED** [review]
functionality-wise LGTM.
would have liked a way to resume the draft, but i assume this can be done in a different PR

**Review by hannyle — APPROVED** [review]
I also think that we should be able to retrieve the draft objects somewhere.
Otherwise, it works fine for me.

**Review by csc-jm — APPROVED** [review]
Adding on to what others mentioned. I was initially confused as well that there doesn't seem to be a way to continue a previous draft yet but that functionality is big enough for another PR. However, I would like to note that in this PR, every auto-save creates a new draft object altogether which I feel is not the desired way. For example if you are filling a form and you fill one field, wait for 5 seconds, then fill another field and wait for another 5 seconds, two different drafts are created even though it would make more sense that the original draft was patched.

Everything else here seems to work as defined in the PR description though so I will also approve this as is.

**Review by lilachic — APPROVED** [review]
This is related to previous reviews, also without changing the same form is possible to be saved multiple times with save button. And here remains a problem with long forms (analysis e.g.), auto-save saves but the form lacks some required fields, making the work flow not so fluent.

**Comment by lilachic** [comment]
And a question about the wizardAlertSlice why it uses the name `name: "draftStatus”, line 7 ?

**Comment by blankdots** [comment]
@saulipurhonen we will move comments on this PR to issues might be good idea to also review those.

**Pull request merged**
