### PR TITLE
add retries & disable also video compression

### PR DESCRIPTION
**Pull request by blankdots**
### Description

Add cypress test retries and disable video compression

### Related issues

hopefully this makes cypress failures not so random

### Type of change

- [x] New feature (non-breaking change which adds functionality)

### Changes Made

1. add 3 retries for CI
2. remove videocompression to make CI run faster.

### Testing

- [x] Tests do not apply

### Mentions

retries **might** cause inconsistencies if data is not cleaned.

### CODE REVIEW

**Review by saulipurhonen — APPROVED** [review]
LGTM

**Review by hannyle — APPROVED** [review]
I suppose setting `"videoCompression": false` also helps reduce the file size ?

**Comment by blankdots** [comment]
> I suppose setting "videoCompression": false also helps reduce the file size ? 

actually does the opposite, there is no video compression at all

**Comment by hannyle** [comment]
> > I suppose setting "videoCompression": false also helps reduce the file size ?
> 
> actually does the opposite, there is no video compression at all

Yep, I just checked from the document: `The compression step will be skipped completely, so the video will be large, but the processing should be faster.`

**Pull request merged**
