### PR TITLE
Edit saved form & replace saved XML functionality

### LINKED ISSUE #144: Add edit and delete functionality to submitted objects
#### Description

We need to be able to resume editing an object, the submission summary on the right hand side should contain a button group with edit and delete

image

The same goes for the summary at the end of the submission:

image

#### DoD (Definition of Done)

Ability to edit and delete submitted objects.

#### Testing

Unit test and Integration testing

### PR DESCRIPTION
**Pull request by saulipurhonen**
### Description

Introduced edit functionality for submitted forms and `replace` functionality for uploaded XML files.

### Related issues

Closes #144 

### Type of change

- [x] New feature (non-breaking change which adds functionality)

### Changes Made

- Added button groups for saved object listing with edit and delete functionalities
- Change `Submit` button type and label according to what user is filling / editing / uploading / replacing
- Renamed `draftObject ` slice to `currentObject`
- Enabled `replace object in folder` so `tags` can be updated
- Show success message with message tied to user action
- Dialog content and functionality for unsaved forms with saved status

### Testing

- [x] E2E test for saved form edit

XML replace testing needs to be done some other way. Issued in #160

### CODE REVIEW

**Comment by saulipurhonen** [comment]
Pushed an test for testing XML replace with Cypress. This fixes #160

**Comment by blankdots** [comment]
@saulipurhonen could we also solve conflicts ? I think merging #159  into develop caused some them.

**Comment by saulipurhonen** [comment]
> @saulipurhonen could we also solve conflicts ? I think merging #159 into`develop` caused some of them.

Conflicts resolved.

**Comment by saulipurhonen** [comment]
> Pushed an test for testing XML replace with Cypress. This fixes #160

For some reason GH actions fails with testing replace XML. Let's do this in different PR.

**Review by blankdots — APPROVED** [review]

**Comment by hannyle** [comment]
So far looks good to me.

One thing I noticed is sometimes when I click to `Edit` a submitted form, it renders like this to me.
Focusing on the input fields would solve the problem, but if I unfocused them, it happened again. This has happened randomly from my side, haven't figured out the pattern.

Screenshot 2021-02-12 at 8 38 53

**Comment by hannyle** [comment]
I have a small question about the code:

In `WizardFillObjectDetailsForm` - function `handleChange`:

> !currentObject.accessionId && currentObjectId
        ? dispatch(
            setCurrentObject({
              ...clone,
              cleanedValues: values,
              type: currentObject.type || "draft",
              objectId: currentObjectId,
            })
          )
        : dispatch(setCurrentObject({ ...clone, cleanedValues: values }))

When will the condition `!currentObject.accessionId && currentObjectId` happen ? I think if `currentObject` doesn't have `accessionId`, will it have a `type` ?

**Comment by saulipurhonen** [comment]
> So far looks good to me.
> 
> One thing I noticed is sometimes when I click to `Edit` a submitted form, it renders like this to me.
> Focusing on the input fields would solve the problem, but if I unfocused them, it happened again. This has happened randomly from my side, haven't figured out the pattern.
> 
> Screenshot 2021-02-12 at 8 38 53

I stumbled into this before but on my local it got fixed with React Hook Form `reset()` function. Let's make an issue when someone finds a way to reproduce this with pattern.

**Comment by saulipurhonen** [comment]
> I have a small question about the code:
> 
> In `WizardFillObjectDetailsForm` - function `handleChange`:
> 
> > !currentObject.accessionId && currentObjectId
> > ? dispatch(
> > setCurrentObject({
> > ...clone,
> > cleanedValues: values,
> > type: currentObject.type || "draft",
> > objectId: currentObjectId,
> > })
> > )
> > : dispatch(setCurrentObject({ ...clone, cleanedValues: values }))
> 
> When will the condition `!currentObject.accessionId && currentObjectId` happen ? I think if `currentObject` doesn't have `accessionId`, will it have a `type` ?

This is a fallback if user saves a draft, edits form and navigates when `draftStatus` is `notSaved`. In this scenario we don't have an accessionId set to currentObject but we have set `currentObjectId`.

This logic could have some improvements.

**Review by hannyle — APPROVED** [review]

**Pull request merged**
